[features]
seeds = true
skip-lint = false
[programs.localnet]
team_dao = "FuQvo5fjJ2A3P3DXgSWsYX8Hsawd2Qg7LwohfSKhEBpu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/fuujack/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
teamdao = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/TeamDao.ts"
tournament = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Tournament.ts"

[test]
startup_wait = 15000

